### ISSUE TITLE
speaker note, previous slide

### ISSUE THREAD

**Issue by Yatima-Kagurazaka** [limhenry/slide#1]
Hi! It's so nice app! 😄 
I want to use speaker note and back to previous slide...!
I think to modify it myself, but I couldn't find server side source code 😞

**Comment by sashokbg** [comment]
Hello @Yatima-Kagurazaka 

I am also interested in this application, but unfortunately I am unable to reach the original author. I am working on my own server side code, but I am having some problems with CORS and SSL.

If you are motivated, we can get in touch and contribute together ?

Best Regards,
Alexander KIRILOV

**Comment by Yatima-Kagurazaka** [comment]
Hi @sashokbg !
That sounds nice, but... how can I contribute?
I don't know much about CORS or SSL... 😢

**Comment by sashokbg** [comment]
@Yatima-Kagurazaka you can contact me at alexander.n.kirilov at gmail.com

**Comment by limhenry** [comment]
hey hey. i will push the code here after google i/o ;)

**Comment by Yatima-Kagurazaka** [comment]
@limhenry wow, nice!
but if you don't want to open the code, it's ok 👍 
I'd like to not look/write the code but rather use these feature.
it's not the metter open or not for me 😉 

@sashokbg for now let me put it on hold, because here he comes!

**Comment by limhenry** [comment]
update:
 - new UI coming soon
 - still finding method to trigger 'previous slide' function 

* how i do that
 - for 'next slide': `document.querySelector('.punch-viewer-container').click()` (simple right?)
 - for 'previous slide': no idea

**Comment by limhenry** [comment]
GOOD NEWS GUYS!

so i found a way to do **previous**/next slide.

major update coming soon!

also, if you have any extra idea, feel free to tell me here ;)

**Comment by Yatima-Kagurazaka** [comment]
wow, great! 😄

**Comment by terpro** [comment]
Is that major update still coming?

**Comment by limhenry** [comment]
Going to release it today/tomorrow

**Comment by limhenry** [comment]
**Sneak Peek!**

![p3](https://user-images.githubusercontent.com/4544770/32494315-1b488978-c3fc-11e7-8708-f7fbf56e3d64.jpg)

**Comment by terpro** [comment]
Oooooo

**Comment by Yatima-Kagurazaka** [comment]
Awesome!
How about speaker notes?
I'll donate some if you do! 😃

**Comment by limhenry** [comment]
I am trying to add that in the next update!

_By the way, what do you mean by "donate"?_

**Comment by Yatima-Kagurazaka** [comment]
I can't wait!
I want to send some money to you if you have "donate button," Patreon account, or something 😉

**Comment by limhenry** [comment]
thanks! ❤️ here you go: [paypal.me/henrylim96](https://paypal.me/henrylim96) 🤗

**Comment by Yatima-Kagurazaka** [comment]
OK, but after next update! 😜

**Comment by limhenry** [comment]
Quick update: I managed to get/fetch the speaker note (though the chrome extension), but now I need to think how should I design the page 🤔

[Screenshot](https://imgur.com/a/IRylp)

**Comment by Yatima-Kagurazaka** [comment]
I think narrow button brings mistap...
How about this;
```
@@@@@@@@
@@@@@@@@
@@@@@@@@
@@@@@@@@
$$$$&&&&
$$$$&&&&
<discon.>
```
@: speaker notes
$: previous slide
&: next slide

**Comment by terpro** [comment]
I think it should be optional, so the previous and next buttons fill the screen _unless_ you enable speaker notes

**Comment by limhenry** [comment]
> "We've detected that your slideshow has speaker notes. Would you like to view them here?"

this is a really really nice idee. thanks!

and yes. the speaker note feature is "optional". 
since the main feature of this app is "Remote", so user won't see the speaker note unless they press on the "show/toggle speaker note" button.

![slides limhenry xyz_653731 nexus 5x](https://user-images.githubusercontent.com/4544770/32555204-178d4b58-c4d7-11e7-95b2-96f77f5a3472.png)
^ Prototype UI (not final)

**Comment by terpro** [comment]
Maybe it should say "Enable speaker notes" if it's not enabled (like in the screenshot) or "Disable speaker notes" if you already enabled them.

**Comment by Yatima-Kagurazaka** [comment]
So can we reconnect easily?
I feel like I'm tapping disconnect by mistake 😆

**Comment by Yatima-Kagurazaka** [comment]
Both ideas sound good! 👍

**Comment by bogas04** [comment]
FWIW here's a shitty mockup for adding speaker notes.

![32555204-178d4b58-c4d7-11e7-95b2-96f77f5a3472](https://user-images.githubusercontent.com/6177621/33366809-663977fe-d512-11e7-9e7e-7479b23a145b.png)

**Comment by limhenry** [comment]
@bogas04 **THANK YOU!** 

anyway, is that better to put the "next/previous button" on the top of the page or bottom?

**Comment by bogas04** [comment]
@limhenry You're welcome !

Bottom would be better, but I just wanted it to be away from DISCONNECT :P

**Comment by limhenry** [comment]
is this ok?
![localhost_8080_100620 nexus 5x](https://user-images.githubusercontent.com/4544770/33432451-efb8c36c-d612-11e7-95c1-c0a4305c4fb8.png)

**Comment by bogas04** [comment]
X to disconnect and 💬 to see notes, right? Looks great !

**Comment by limhenry** [comment]
![untitled-1](https://user-images.githubusercontent.com/4544770/33437602-750e5b3e-d623-11e7-8c5b-409b5027a815.jpg)

**Comment by limhenry** [comment]
and desktop mode 😄 

![2](https://user-images.githubusercontent.com/4544770/33437938-66c45b2c-d624-11e7-8822-bb80a77dcda2.jpg)

**Comment by terpro** [comment]
@limhenry Looks great!

**Comment by limhenry** [comment]
@bogas04 @terpro @Yatima-Kagurazaka 
I just deployed the new version of Remote for Google Slides (v2.0.2) 😄 
Timer and speaker note is now available in the latest version! 🎉 
Feel free to contact me if you having any problems/bugs. 🤓 
Thanks for the support!

**Comment by Yatima-Kagurazaka** [comment]
Thanks! I donated some to you just now! 😉

**Comment by limhenry** [comment]
@Yatima-Kagurazaka Thank you very much! 😃
