### ISSUE TITLE
Does not properly handle animations

### ISSUE THREAD

**Issue by terpro** [limhenry/slide#2]
When you have a slideshow with animations, clicking on next won't go to the next slide, but rather play the next animation. The slide number will increase but it won't have changed slides. If the first or last slide has animations, you won't be able to play them because the next button will be greyed out.

Just make a slideshow with animations and you'll see what I'm talking about.

https://user-images.githubusercontent.com/11605395/32525027-66aa147e-c3d7-11e7-9b7d-c14c4af5e1d8.jpg
https://user-images.githubusercontent.com/11605395/32525028-66c43d0e-c3d7-11e7-90c5-a6435b51e7c8.jpg

A temporary fix is to add a blank first and last slide to your presentation.

**Comment by limhenry** [comment]
Thank you!!! I will try to fix this in the next update!

**Comment by limhenry** [comment]
Update: will fix this in version 2.0.4

**Comment by limhenry** [comment]
This bug is fixed in the latest update! 
https://twitter.com/henrylim96/status/939438624528936960
