### ISSUE TITLE
Need a easier way to start "Presenter Mode"

### ISSUE THREAD

**Issue by limhenry** [limhenry/slide#5]
**Current problem**: User needs to modify the URL themselves. 
**Proposed solution**: Adding a button in the edit mode. _(See screenshot below)_

Good idea? Bad idea?

![screen shot 2017-12-04 at 11 24 05 pm](https://user-images.githubusercontent.com/4544770/33560415-a01835dc-d94a-11e7-8dc7-643f88f6b008.png)

**Comment by terpro** [comment]
Maybe make it a little smaller

**Comment by limhenry** [comment]
haha i am thinking the same thing too. the button is too long 😅

**Comment by limhenry** [comment]
This feature is now available in the latest update! https://twitter.com/henrylim96/status/939438624528936960
