### ISSUE TITLE
Do not work on  Mac OS Sierra

### ISSUE THREAD

**Issue by kunalkushwaha** [limhenry/slide#7]
It works on Windows and Linux, but do not work on Mac.

The pop-up for key do not appear.

**Comment by kunalkushwaha** [comment]
Slide : https://docs.google.com/presentation/d/1HBiiJEYFnvdGFhkVyww99Bt2nT0OpR_UD0W6VZsRoks/edit?usp=sharing

PIN: **Issue is no PIN is generated.**

Browser language: English (United States)

Browser Version: `Version 63.0.3239.84 (Official Build) (64-bit)`

@limhenry Updated with requested details.

**Comment by limhenry** [comment]
Please take note the app/extension will only works if you open the slides in [**present mode**](https://docs.google.com/presentation/d/1HBiiJEYFnvdGFhkVyww99Bt2nT0OpR_UD0W6VZsRoks/present?slide=id.p). Anyway, I will include a "Reset PIN" button in the next update, just in case something wrong with the PIN or whatever :)

**Comment by kunalkushwaha** [comment]
Thanks for quick response :)

Yes, I open the slide in  "Present mode", but it does not show the PIN.
On my windows and linux machine, same browser and slide, I am able to see the PIN.

**Comment by limhenry** [comment]
Can you try to uninstall the extension and reinstall back? (That's a very weird bug tbh) Thanks btw :)

**Comment by kunalkushwaha** [comment]
I tried , but still same issue.

**Comment by kunalkushwaha** [comment]
In Developer Tools, Console I see these messages. 

```
The key "target-densitydpi" is not supported.
present?slide=id.p:1 WebSocket connection to 'wss://remoteforgs.firebaseio.com/.ws?v=5' failed: WebSocket is closed before the connection is established.
3firebase.js:416 WebSocket connection to 'wss://remoteforgs.firebaseio.com/.ws?v=5' failed: WebSocket opening handshake timed out
Yf.open @ firebase.js:416
(anonymous) @ firebase.js:431
```

Does while creating socket, system Proxy setting is considered?

**Comment by kunalkushwaha** [comment]
Its Confirmed. It is Proxy issue. I verified it on non-proxy network.
It works perfectly :)

You may close this issue :)

**Comment by limhenry** [comment]
Thanks for letting me know!
